spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/corona?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Sql(88)Pass

  jpa:
    hibernate:
      ddl-auto: update
    #         database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

